#! /bin/sh

if [[ $(diff /etc/wpa_supplicant.conf /usr/pi-config/wpa_supplicant.conf) ]]; then
   echo "Wifi already configured"
else
   echo "Configuring Wifi"
   sudo rm /etc/wpa_supplicant.conf
   cp /usr/pi-config/wpa_supplicant.conf rm /etc/wpa_supplicant.conf
   wpa_cli reconfigure
fi



